SELECT CONVERT(VARCHAR, GETDATE(), 101) AS TodayDateStyle
UNION
SELECT CONVERT(VARCHAR, GETDATE(), 103) AS TodayDateStyle
UNION
SELECT CONVERT(VARCHAR, GETDATE(), 110) AS TodayDateStyle
UNION
SELECT CONVERT(VARCHAR, GETDATE(), 120) AS TodayDateStyle
UNION
SELECT CONVERT(VARCHAR, GETDATE(), 112) AS TodayDateStyle;
